### PR TITLE
Custom lodash update

### PR DESCRIPTION
**Pull request by janzheng**
Hey there, I removed `lodash` as a requirement from `package.json` and included a custom lodash file in `other/lodash.min.js`. The generator command is in a line in package.json called `genlodash` in case it needs to be appended.

I also added a new grunt command to build a browserified version, and regenerated the `airtable.browser.js` build. It's a lot smaller now (from 646kb to 144kb)!

### CODE REVIEW

**Comment by EvanHahn** [comment]
Would we instead be able to only require the pieces we need (for example, `require('lodash/isArray')` instead of having to include a custom Lodash build?

**Comment by janzheng** [comment]
That's a good point, and that's entirely up to you — doing it that way will increase flexibility and ease development, but it would add slightly more size to the build. I was trying to make the browser build as tiny as possible by removing as much extra lodash stuff as possible

**Comment by EvanHahn** [comment]
Interesting—how will that increase the size of the build? I would expect the build sizes to be equivalent.

**Comment by janzheng** [comment]
I tried using various `require`s, and I expected it to be the same, but it
actually increases the file size from 144kb to 277kb. I suspect it's
because it just uses the un-minified lodash, which comes with lots of
comments. With gzip this is probably makes a negligible difference, though.

Another side effect of using various `require`s forces the source code to
be changed — I prefer just using regular lodash syntax `_.isArray` instead
of redefining an `isArray` — whatever additional lodash functionality you
need you can just regenerate.

In my humble opinion, I'd still prefer the custom lodash solution for
generation a slightly smaller airtable browser library
cheers!

**Comment by EvanHahn** [comment]
I'm going to close this issue because we'll soon release a version that lowers the minified size to 122 KB. Thanks for bringing this to our attention—we'll update you when we release the new version.

**Comment by janzheng** [comment]
Exciting! thanks for all your hard work

**Comment by EvanHahn** [comment]
We just released `airtable@0.5.8` which shrinks the minified size by almost half. Thanks for bringing this up with us!

**Comment by janzheng** [comment]
Awesome!! Great work, guys!

**Pull request closed without merging**
