### PR TITLE
Fix github lint warnings

### PR DESCRIPTION
**Pull request by mzgoddard**

### CODE REVIEW

**Comment by jugglinmike** [comment]
@mzgoddard The project's `npm run lint` command reports several warnings before and after this patch is applied. Where is "github lint" defined?

**Comment by mzgoddard** [comment]
@jugglinmike github lint refers to the lint warnings displayed on the other PRs. https://github.com/Airtable/airtable.js/pull/224/files under **Unchanged files with check annotations**

**Comment by jugglinmike** [comment]
Thanks, Z! I have a few more questions

How is that task configured? Is it possible to run it locally? Do the results truly differ from the results of `npm run lint`?

When I review the change set for this patch on GitHub.com, I see "Check warning" annotations. Is this patch intended to address those?

**Comment by mzgoddard** [comment]
@jugglinmike ah, you're right. I'm not sure why I thought the github lint and npm lint are different. As you point out, I did miss a lot of warnings too.

I've posted a change that gets the remaining syntax warnings. There are a lot of type warnings remaining I think that should be handled in another branch so we can get these easier changes out of the way.

**Comment by mzgoddard** [comment]
The force push rewording the latest commit. It was pointing at the wrong target commit.

**Review by benrazon — APPROVED** [review]

**Pull request merged**
