### PR TITLE
Adding debug mode to request module at base.js

### PR DESCRIPTION
**Pull request by FernandoKGA**
This PR adds _debug mode_ at the `request` module in `base.js`, however I couldn't find a way to test it, as the module is an variable at the base.js.
If anyone can test it, I would appreciate.

### CODE REVIEW

**Comment by alexsorokin-at** [comment]
Is it the same as running with `NODE_DEBUG=request` environment variable set?

**Comment by FernandoKGA** [comment]
> Is it the same as running with `NODE_DEBUG=request` environment variable set?

Yes, it is. But for some reason `NODE_DEBUG=request` doesn't work with `airtable.js`, like if it doesn't recognize it...

**Comment by FernandoKGA** [comment]
I used this script to test it:

```js
const Airtable = require('../airtable.js/airtable');

async function test() {
    let debug = true;
    let base = new Airtable({apiKey: 'key'}).base('base', debug);
    try {
         let result = await base('Test').select({}).all();
    }
    catch (err) {
         console.error(err);
    }
}
```

And using NODE_DEBUG=request, without the code I have just added, doesn't make any difference...

**Comment by alexsorokin-at** [comment]
You should try console.log(process.env.NODE_DEBUG) - it's likely the env variable isn't set somehow. You can also try doing `process.env.NODE_DEBUG = 'request'` in JS.

I'm going to close this PR as NODE_DEBUG provides this functionality.

**Comment by FernandoKGA** [comment]
@alexsorokin-at Managed to make it work with your tips, thanks.

**Pull request closed without merging**
